package carrentalsystem;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import java.util.*;
import java.util.stream.Collectors;

public class CarRentalSystem {
    private List<User> loggedInUsers; // List of logged-in users
    private List<Branch> branches; // List of branches in the system
    private List<RentalBooking> bookings; // List of all bookings

    // Constructor
    public CarRentalSystem() {
        this.loggedInUsers = new ArrayList<>();
        this.branches = new ArrayList<>();
        this.bookings = new ArrayList<>();
    }

    // User Management
    public void login(User user) {
        loggedInUsers.add(user);
        System.out.println(user.getName() + " logged in.");
    }

    public void logout(User user) {
        loggedInUsers.remove(user);
        System.out.println(user.getName() + " logged out.");
    }



    public List<Branch> getBranchByLocation(Location location) {
        return null;
    }

    public List<Branch> getAllBranches() {
        return null;
    }

    // Car Search by Location, Start Date, and End Date
    public List<Car> searchAvailableCars(String location, Date startDate, Date endDate) {
        return null;
    }

    //book a car by branch Id , car Id , location , startDate , endDate
    public RentalBooking makeReservation(BookingRequest bookingRequest) {
            // check if the car is booked or not before booking
            // ask the user their preferable mode of payment and make a request to payment server/payment method by using bill class
            // confirm payment generate a receipt for them and allocate the car.
            // add the booking and receipt to the user for their reference
        return null;
    }

    private void getBranchById(int branchId) {
    }

    public PaymentDetails processPayment(Bill bill) {
        // takes the bill generated by the booking opens up payment gateway for them and let them make a payment after
        //  successful booking generate a receipt or a rental booking
        return null;
    }

    public PaymentDetails getReceipt(int bookingId) {
        return null;
    }
}